// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-1",
    "aws_content_delivery_bucket": "clientboilerplate-20180927142021--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-southeast-1",
    "aws_content_delivery_url": "http://clientboilerplate-20180927142021--hostingbucket.s3-website-ap-southeast-1.amazonaws.com"
};


export default awsmobile;
